# Generated by Django 3.2 on 2022-09-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bouquets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bouquet',
            name='sku',
            field=models.CharField(max_length=20),
        ),
    ]
