# Generated by Django 3.2 on 2022-11-02 18:11

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bouquets', '0002_alter_bouquet_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bouquet',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('15.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
    ]
