# Generated by Django 3.2 on 2022-10-15 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'Enquiries'},
        ),
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(choices=[('Bouquets', 'Bouquets'), ('Order', 'Order'), ('Delivery', 'Delivery'), ('Account', 'Account'), ('Other', 'Other')], default='Bouquets', max_length=20),
        ),
    ]
