# Generated by Django 3.2 on 2022-10-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20221015_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(choices=[('Bouquets', 'Bouquets'), ('Order', 'Order'), ('Delivery', 'Delivery'), ('Account', 'Account'), ('Other', 'Other')], max_length=20),
        ),
    ]
