# Generated by Django 3.2 on 2022-10-18 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_auto_20221017_2015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Enquiries'},
        ),
    ]
