# Generated by Django 3.2 on 2022-10-20 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='image-coming-soon.jpg', null=True, upload_to=''),
        ),
    ]
